import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "ICCS",
  description: "Generated by create next app",
   icons: {
    icon: "/iccs-rounded-logo.png", // yahan tumhari logo image public folder me honi chahiye
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {/* Navbar is client component, safe */}
        <Navbar />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
